import React, { useEffect, useState } from 'react';
import CryptoJS from 'crypto-js';

const SecretGenerator = () => {
  const [secret, setSecret] = useState('');
  const [newSecret, setNewSecret] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [loggedIn, setLoggedIn] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');

  const generateSecret = () => {
    // Generate a random secret
    const newSecret = Math.random().toString(36).slice(2);
    setSecret(newSecret);
    localStorage.setItem('secret', encryptSecret(newSecret, password));
  };

  const saveSecret = (newSecret) => {
    // Generate a random secret
    setSecret(newSecret);
    localStorage.setItem('secret', encryptSecret(newSecret, password));
  };

  const generateSecretToShow = () => {
    // Generate a random secret
    const newSecret = Math.random().toString(36).slice(2);
    setNewSecret(newSecret);
  };

  useEffect(() => {
    // Update the document title using the browser API
    const encryptedSecret = localStorage.getItem('secret');
    if (encryptedSecret) {
      setSecret(encryptedSecret);
    } else {
      generateSecretToShow();
    }
  }, []);

  const encryptSecret = (secret, password) => {
    // Encrypt the secret using AES encryption and the password as the key
    return CryptoJS.AES.encrypt(secret, password).toString();
  };

  const decryptSecret = (encryptedSecret, password) => {
    // Decrypt the encrypted secret using AES decryption and the password as the key
    return CryptoJS.AES.decrypt(encryptedSecret, password).toString(CryptoJS.enc.Utf8);
  };

  const handleVerifySecret = () => {
    if (password.trim() === '') {
      setErrorMessage('Password is required');
    } else {
      try {
        const encryptedSecretKey = localStorage.getItem('secret');
        let plainSecretText = decryptSecret(encryptedSecretKey, password);
        if (!plainSecretText) {
          setErrorMessage('System is unable to authenticate you');
        } else {
          setLoggedIn(true);
          setErrorMessage('');
        }
      } catch (e) {
        setErrorMessage('System is unable to authenticate you');
      }
    }
  };

  const handleNextClick = () => {
    if (password.trim() === '' || confirmPassword.trim() === '') {
      setErrorMessage('Both password fields are required');
    } else if (password === confirmPassword) {
      saveSecret(newSecret);
      setLoggedIn(true);
      setErrorMessage('');
    } else {
      setErrorMessage('Passwords do not match!');
    }
  };

  const handleLogoutClick = () => {
    // localStorage.removeItem('secret');
    setPassword('');
    setConfirmPassword('');
    setLoggedIn(false);
  };

  const handleResetClick = () => {
    localStorage.clear();
    setSecret('');
    setPassword('');
    setConfirmPassword('');
    setLoggedIn(false);
    generateSecretToShow();
  };

  if (loggedIn) {
    // Logged in user: show secret, regenerate button, and logout button
    const encryptedSecret = localStorage.getItem('secret');
    const decryptedSecret = decryptSecret(encryptedSecret, password);
    return (
      <div>
        <p>Your secret: {decryptedSecret || 'None'}</p>
        <button onClick={generateSecret}>Regenerate</button>
        <button onClick={handleLogoutClick}>Logout</button>
      </div>
    );
  } else if (
    secret && !loggedIn) {
    return (
      <div>
        <input type="password" placeholder="Enter password" value={password} onChange={(e) => setPassword(e.target.value)} />
        <button onClick={handleVerifySecret}>Next</button>
        <br />
        <button onClick={handleResetClick}>Reset</button>
        {errorMessage}
      </div>
    )
  }
  else {
    // New user: show autogenerated secret and password fields
    return (
      <div>
        <p>Your secret: {newSecret || 'None'}</p>
        <input type="password" placeholder="Enter password" value={password} onChange={(e) => setPassword(e.target.value)} />
        <input type="password" placeholder="Confirm password" value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} />
        <button onClick={handleNextClick}>Next</button>
      </div>
    );
  }
};

export default SecretGenerator;
